blog/urls.py
from unicodedata import name
from django.urls import path,include
from blog.views import index_blog,single_blog,search_blog
from blog.feeds import LatestEntriesFeed
app_name = "blog"
urlpatterns = [
    path('', index_blog, name="index"),
    path('single/<int:id>', single_blog, name="single"),
    path('category/<str:cat_name>',index_blog,name='category'),
    path('authors/<str:author_username>',index_blog,name='author'),
    path('tag/<str:tag_name>',index_blog,name='tag'),
    path('search',search_blog,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    

]

siteino/urls.py
from django.contrib import admin
from comingsoon.views import splashview
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views
sitemaps = {
    'static': StaticViewSitemap,
    'blog':BlogSitemap,
}


urlpatterns = [
    path("ads.txt", views.ads, name="ads"),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    # url(r'^(?!.*admin|ads\.txt|sitemap\.xml).*', splashview,name='comingsoon'),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/',include('accounts.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main/password/password_reset_complete.html'), name='password_reset_complete'), 
    path("password_reset/", views.password_reset_request, name="password_reset"), 
]
handler404 = "siteino.views.page_not_found_view"

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

website/urls.py
from django.urls import path,include
from website.views import index_view,about_view,contact_view,newsletter_view
app_name = "website"
urlpatterns = [
    path('', index_view, name="index"),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=300)
    
    def __str__(self):
        return self.name
    
class Post(models.Model):
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=300)
    content = models.TextField()
    category = models.ManyToManyField(Category)
    tag = TaggableManager()
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require =  models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"({self.id}) {self.title}"
    
    class Meta:
        ordering =['-published_date']

    # def truncate_string(self):
    #     return self.content[:100]+" ... "
    
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'id':self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    subject =  models.CharField(max_length=250)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created_date']

blog/forms.py
from django.forms import ModelForm
from blog.models import Comment
from captcha.fields import CaptchaField

class CommentModelForm(ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = '__all__'


        

blog/views.py
from django.shortcuts import get_object_or_404, render,redirect
from blog.models import Post,Comment
import datetime
from django.db.models.functions import Now
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from blog.forms import CommentModelForm
from django.contrib import messages

# Create your views here.


# def index_blog(request,cat_name=None,author_username=None):
#     posts = Post.objects.filter(status=1)
#     # current_datetime = datetime.datetime.now()
#     # posts = posts.filter(published_date__lte=current_datetime)
#     posts = posts.filter(published_date__lte=Now())
#     posts = posts.order_by('published_date')
#     if cat_name != None:
#         posts = posts.filter(category__name=cat_name)
#     if author_username != None:
#         posts = posts.filter(author__username=author_username)
#     content={'posts':posts}
#     return render(request, 'blog/blog-home.html',content)

def index_blog(request,**kwargs):
    posts = Post.objects.filter(status=1)
    # current_datetime = datetime.datetime.now()
    # posts = posts.filter(published_date__lte=current_datetime)
    posts = posts.filter(published_date__lte=Now())
    posts = posts.order_by('-published_date')
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs.get('cat_name'))
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs.get('author_username'))
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tag__name__in=[kwargs.get('tag_name')])
    paginator = Paginator(posts,3)
    try:
        number_page = request.GET.get('page')
        posts = paginator.page(number_page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    content={'posts':posts}
    return render(request, 'blog/blog-home.html',content)

    
def single_blog(request,id):
    update_views = Post.objects.get(pk=id)
    update_views.counted_views += 1
    update_views.save()
    posts = Post.objects.filter(status=1)
    posts = posts.filter(published_date__lte=datetime.datetime.now())
    posts = get_object_or_404(posts, pk=id)
    
    comments = Comment.objects.filter(post=id,approved=True)
    
    view_post = Post.objects.filter(status=1)
    current_datetime = datetime.datetime.now()
    view_post = view_post.filter(published_date__lte=current_datetime)
    view_post = view_post.order_by('-published_date')
    list_view_post = list(view_post)
    post_count = len(list_view_post)
    post_index = list_view_post.index(Post.objects.get(pk=id))
    if post_count==1 :
        prev_post = None
        next_post = None
    elif post_count==2:
        if post_index==0:
            prev_post = None
            next_post = list_view_post[1]
        elif post_index==1:
            prev_post = list_view_post[0]
            next_post = None
    elif post_count>2:
        if post_index == post_count-1:
            prev_post = list_view_post[post_count-2]
            next_post = None
        elif post_index == 0:
            prev_post = None
            next_post = list_view_post[1]
        elif post_index>0 and post_index<post_count-1:
            prev_post = list_view_post[post_index-1]
            next_post = list_view_post[post_index+1]
    if request.method=="POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'The comment was successfully submitted')
        else:
            messages.error(request,'There was a problem registering the comment')
    
    form_comment=CommentModelForm()
    
    next = request.GET.get('next')
    print(next)
    content = {'posts':posts,'comments':comments,'next':next_post,'prev':prev_post,'form':form_comment}
    if not posts.login_require:   
        return render(request, 'blog/blog-single.html',content)
    else :
        if request.user.is_authenticated:
            return render(request, 'blog/blog-single.html',content)
        else:
            return redirect(f'/accounts/login/?next={next}')

def search_blog(request):
    posts = Post.objects.filter(status=1)
    posts = posts.filter(published_date__lte=Now())
    posts = posts.order_by('published_date')
    if s := request.GET.get('s'): #walrus oprator
        posts=posts.filter(content__contains=s)
    content={'posts':posts}
    return render(request, 'blog/blog-home.html',content)

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static "img/blog/ads-banner.jpg" %}"alt=""></a>
</div>

templates/blog/blog-home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load humanize %}
{% load blog_tags %}

			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static "img/blog/cat-widget1.jpg" %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static "img/blog/cat-widget2.jpg" %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static "img/blog/cat-widget3.jpg" %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										<!-- {% for cat in post.category.all %}
										<li><a href="#">{{cat.name}}, </a></li>
										{% endfor %} -->
										<!-- OR -->
										{% for cat in post.category.all %}
											<li><a href={% url 'blog:category' cat_name=cat.name %}>{{ cat.name }}
											{%if not forloop.last%},{%endif%}</a></li>
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href={% url 'blog:author' author_username=post.author.username %}>{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|naturalday}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comments_count post.id %} Comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<a href={% url 'blog:single' id=post.id %}><img class="img-fluid" src="{{ post.image.url }}" alt=""></a>
									</div>
									<a class="posts-title" href="{% url 'blog:single' id=post.id %}?next={% url 'blog:single' id=post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content|truncatewords:16}}
									</p>
									<a href={% url 'blog:single' id=post.id %} class="primary-btn">View More</a>
								</div>
							</div>
							{% endfor %}						
		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">

									{% if posts.has_previous %}
									<li class="page-item">
										<a href="?page=1" class="page-link" aria-label="First Posts">
											<span aria-hidden="true">
												<span class="lnr lnr-arrow-left"></span>
											</span>
										</a>
									</li>

									<li class="page-item">
										<a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
											<span aria-hidden="true">
												<span class="lnr lnr-chevron-left"></span>
											</span>
										</a>
									</li>
									{% endif %}

									{% for num in posts.paginator.page_range %}
									{% if posts.number == num %}
		                            	<li class="page-item active"><a href="?page={{num}}" class="page-link">{{num}}</a></li>
									{% else %}
		                            	<li class="page-item"><a href="?page={{num}}" class="page-link">{{num}}</a></li>
									{% endif %}	
									{% endfor %}

									{% if posts.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{posts.next_page_number}}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>

									<li class="page-item">
		                                <a href="?page={{posts.paginator.num_pages}}" class="page-link" aria-label="Latest Posts">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-arrow-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}


		                        </ul>
		                    </nav>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								
								{% include 'blog/blog-search.html' %}

								{% include 'blog/blog-writer.html' %}

								{% latest_posts 3 %}

								{% include 'blog/blog-ads.html' %}

								{% postcategories %}

								{% include 'blog/blog-newsletter.html' %}

								{% authors %}

							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->

{% endblock %}

templates/blog/blog-latest-posts.html
{% load static %}
{% load humanize %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    {% for post in posts %}
    <div class="popular-post-list">
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src={{ post.image.url }} alt="">
            </div>
            <div class="details">
                <a href={% url 'blog:single' id=post.id %}><h6>{{post.title}}</h6></a>
                <p>{{post.published_date|naturaltime}}</p>
            </div>
        </div>													
    </div>
    {% endfor %}
</div>

templates/blog/blog-newsletter.html
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
        Here, I focus on a range of items and features that we use in life without
        giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
       <div class="col-autos">
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
            </div>
            </div>
            <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
          </div>
        </div>
        <a href="#" class="bbtns">Subcribe</a>
    </div>	
    <p class="text-bottom">
        You can unsubscribe at any time
    </p>								
</div>

templates/blog/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for cat in categories%}
        <li>
            <a href={% url 'blog:category' cat_name=cat.name %} class="d-flex justify-content-between">
                <p>{{cat.name}}</p>
                <p>{{cat.post__count}}</p>
            </a>
        </li>	
        {% endfor %}													
    </ul>
</div>	

templates/blog/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action={% url 'blog:search' %} method="GET">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load blog_tags %}
{% load humanize %}
		  
			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{posts.title}}				
							</h1>	
							<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span class="lnr lnr-arrow-right"></span> {{posts.title}}</p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{ posts.image.url }}"alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for post in posts.category.all %}
										<li><a href={% url 'blog:category' cat_name=post.name %}>{{ post.name }}
											{% if not forloop.last %},{% endif %} </a></li>
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{posts.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{posts.published_date|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{posts.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{posts.title}}</h3>
									<p class="excert">
										{{posts.content|safe}}
									</p>

								</div>
							</div>
							<div class="navigation-area">
								<div class="row">
									{% if not prev %}
										<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
											<div class="detials">
											</div>
										</div>
									{% elif prev %}
										<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
											<div class="thumb">
												<a href={% url 'blog:single' id=prev.id %}><img class="img-fluid" src="{{ prev.image.url }}"alt=""></a>
											</div>
											<div class="arrow">
												<a href="{% url 'blog:single' id=prev.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
											</div>
											<div class="detials">
												<p>Prev Post</p>
												<a href="{% url 'blog:single' id=prev.id %}"><h4>{{prev.title}}</h4></a>
											</div>
										</div>
									{% endif %}
									


									{% if not next %}
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										<div class="detials">
										</div>
									</div>
									{% elif next %}
										<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
											<div class="detials">
												<p>Next Post</p>
												<a href={% url 'blog:single' id=next.id %}><h4>{{next.title}}</h4></a>
											</div>
											<div class="arrow">
												<a href={% url 'blog:single' id=next.id %}><span class="lnr text-white lnr-arrow-right"></span></a>
											</div>
											<div class="thumb">
												<a href={% url 'blog:single' id=next.id %}><img class="img-fluid" src="{{ next.image.url }}"alt=""></a>
											</div>										
										</div>
									{% endif %}
									
								</div>
							</div>
							<!--
							<div class="comments-area">
								<div id="disqus_thread"></div>
									<script>
										/**
										*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
										*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
										/*
										var disqus_config = function () {
										this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
										this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
										};
										*/
										(function() { // DON'T EDIT BELOW THIS LINE
										var d = document, s = d.createElement('script');
										s.src = 'https://http-127-0-0-1-8000-vieb7h3z2t.disqus.com/embed.js';
										s.setAttribute('data-timestamp', +new Date());
										(d.head || d.body).appendChild(s);
										})();
									</script>
									<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
								</div>
							</div>
							-->

							<div class="comments-area">
								<h4>{{comments|length}} Comments</h4>
								{% for comment in comments %}
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static "img/blog/c1.jpg" %}"alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{comment.name}}</a></h5>
                                                <p class="date">{{comment.created_date|naturaltime}}</p>
                                                <p class="comment">
                                                    {{comment.message}}
                                                </p>
                                            </div>
                                        </div>
										<!--
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div>
										-->
                                    </div>
                                </div>	
								{% endfor %}                                             				
							</div>
							<div class="comment-form">
								<h4>Leave a Comment</h4>
								<form action={% url 'blog:single' id=posts.id %} method="post">
									{% csrf_token %}
									<div class="form-group form-inline">
										<input type="hidden" name="post" value={{posts.id}}>
										{% if request.user.is_authenticated %}
									  <div class="form-group col-lg-6 col-md-12 name">
									    <input type="hidden" value={{request.user.first_name}} class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="hidden" value={{request.user.email}} class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>
									  {% else %}
									  <div class="form-group col-lg-6 col-md-12 name">
									    <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>
									  {% endif %}
									</div>
									<div class="form-group">
										<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
									<div>
										{{form.captcha}}
									</div><br><br><br>
									<button type="submit" class="primary-btn text-uppercase">Post Comment</button>	
								</form>
							</div>

						</div>


						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								
								{% include 'blog/blog-search.html' %}

								{% include 'blog/blog-writer.html' %}

								{% latest_posts 4 %}

								{% include 'blog/blog-ads.html' %}

								{% postcategories %}

								{% include 'blog/blog-newsletter.html' %}

								{% include 'blog/blog-tags.html' %}	

							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-tags.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in posts.tag.all %}
        <li><a href={% url 'blog:tag' tag_name=tag.name %}>{{tag.name}}</a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static "img/blog/user-info.png" %}" alt="">
    <a href="#"><h4>Charlie Barber</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
    </p>
</div>

templates/blog/blog_athor.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Authors</h4>
    <ul>
        {% for author in authors %}
        <li><a href={% url 'blog:author' author_username=author.username %}>{{author.get_full_name}}</a></li>
        {% endfor %}
    </ul>
</div>