accounts/urls.py
from django.urls import path
from accounts.views import login_view,signup_view,logout_view
app_name = "accounts"
urlpatterns = [
    # login
    path('login/', login_view, name="login"),
    # logout
    path('logout/',logout_view,name='logout'),
    # signup
    path('signup/',signup_view,name='signup'),
]

blog/urls.py
from unicodedata import name
from django.urls import path,include
from blog.views import index_blog,single_blog,search_blog
from blog.feeds import LatestEntriesFeed
app_name = "blog"
urlpatterns = [
    path('', index_blog, name="index"),
    path('single/<int:id>', single_blog, name="single"),
    path('category/<str:cat_name>',index_blog,name='category'),
    path('authors/<str:author_username>',index_blog,name='author'),
    path('tag/<str:tag_name>',index_blog,name='tag'),
    path('search',search_blog,name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    

]

siteino/urls.py
from django.contrib import admin
from comingsoon.views import splashview
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views
sitemaps = {
    'static': StaticViewSitemap,
    'blog':BlogSitemap,
}


urlpatterns = [
    path("ads.txt", views.ads, name="ads"),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    # url(r'^(?!.*admin|ads\.txt|sitemap\.xml).*', splashview,name='comingsoon'),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/',include('accounts.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="main/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main/password/password_reset_complete.html'), name='password_reset_complete'), 
    path("password_reset/", views.password_reset_request, name="password_reset"), 
]
handler404 = "siteino.views.page_not_found_view"

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

website/urls.py
from django.urls import path,include
from website.views import index_view,about_view,contact_view,newsletter_view
app_name = "website"
urlpatterns = [
    path('', index_view, name="index"),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),
]

comingsoon/models.py
from django.db import models

class Notify_Me(models.Model):
    email = models.EmailField(unique=True)
    created_date = models.DateTimeField(auto_now_add=True)  
    
    def __str__(self):
        return self.email
    
    class Meta:
        ordering = ['-created_date']

comingsoon/forms.py
from django.forms import ModelForm
from comingsoon.models import Notify_Me
from captcha.fields import CaptchaField

class ComingsoonModelForm(ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Notify_Me
        fields = '__all__'


        

comingsoon/views.py
from django.shortcuts import render
from comingsoon.forms import ComingsoonModelForm
from django.shortcuts import render
from django.contrib import messages

def splashview(request):
    if request.method=="POST":
        form = ComingsoonModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'The email was successfully submitted')
        else:
            messages.error(request,'There was a problem registering the comment')
            
    form=ComingsoonModelForm()
    content = {'form':form}
    return render(request, 'comingsoon.html',content)

templates/base.html
{% load static %}
<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static "img/fav.png" %}">
		<!-- Author Meta -->
		<meta name="author" content="colorlib">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Travel</title>

		{% block head %}
		{% endblock %}
		
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
		<!--
			CSS
			============================================= -->
			{% load compress %}
			{% compress css %}
			<link rel="stylesheet" href={% static "css/linearicons.css" %}>
			<link rel="stylesheet" href={% static "css/font-awesome.min.css" %}>
			<link rel="stylesheet" href={% static "css/bootstrap.css" %}>
			<link rel="stylesheet" href={% static "css/magnific-popup.css" %}>
			<link rel="stylesheet" href={% static "css/jquery-ui.css" %}>
			<link rel="stylesheet" href={% static "css/nice-select.css" %}>
			<link rel="stylesheet" href={% static "css/animate.min.css" %}>
			<link rel="stylesheet" href={% static "css/owl.carousel.css" %}>
			<link rel="stylesheet" href={% static "css/main.css" %}>
			{% endcompress %}

		</head>
		<body>
			<header id="header">
				{% include 'message.html' %}
				<div class="header-top">
					<div class="container">
						<div class="row align-items-center">
							<div class="col-lg-6 col-sm-6 col-6 header-top-left">
								<ul>
									{% if request.user.is_authenticated %}
										<li><a href="#">Logged in as {{request.user.username}}</a></li>
										<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
									{% else %}
										<li><a href="{% url 'accounts:login' %}">Login</a></li>
										<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
									{% endif %}
								</ul>
							</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
					</div>
				</div>
			</div>
			<div class="container main-menu">
				<div class="row align-items-center justify-content-between d-flex">
					<div id="logo">
						<a href="{% url "website:index" %}"><img src="{% static "img/logo.png" %}" alt="" title="" /></a>
					</div>
					<nav id="nav-menu-container">
						<ul class="nav-menu">
							<li><a href="{% url "website:index" %}">Home</a></li>
							<li><a href="{% url "website:about" %}">About</a></li>
							<li><a href="{% url "blog:index" %}">Blog</a></li>
							<li><a href="{%  url "website:contact" %}">Contact</a></li>
				        </ul>
					</nav><!-- #nav-menu-container -->
				</div>
			</div>
		</header><!-- #header -->
		
		
			
		{% block content %}
		
		
        {% endblock %}
		
		
		
		<!-- start footer Area -->
			<footer class="footer-area section-gap">
				<div class="container">
					
					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="#">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="#">Blog</a></li>
											<li><a href="#">Contact</a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.
								</p>
								<div>
									<form action={% url 'website:newsletter' %} method="post" class="subscription relative">
										<div class="input-group d-flex flex-row">
											{% csrf_token %}
											<input name="email" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button type='submit' class="btn bb-btn"><span class="lnr lnr-location"></span></button>
										</div>
										<div class="mt-10 info"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static "img/i1.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i2.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i3.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i4.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i5.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i6.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i7.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i8.jpg" %}" alt=""></li>
								</ul>
							</div>
						</div>
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->
			{% load compress %}
			{% compress js %}
			<script src="{% static "js/vendor/jquery-2.2.4.min.js" %}"></script>
			<script src="{% static "js/popper.min.js" %}"></script>
			<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
 			<script src="{% static "js/jquery-ui.js" %}"></script>
  			<script src="{% static "js/easing.min.js" %}"></script>
			<script src="{% static "js/hoverIntent.js" %}"></script>
			<script src="{% static "js/superfish.min.js" %}"></script>
			<script src="{% static "js/jquery.ajaxchimp.min.js" %}"></script>
			<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
			<script src="{% static "js/jquery.nice-select.min.js" %}"></script>
			<script src="{% static "js/owl.carousel.min.js" %}"></script>
			<script src="{% static "js/mail-script.js" %}"></script>
			<script src="{% static "js/main.js" %}"></script>
			{% endcompress %}
		</body>
	</html>

templates/comingsoon.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Coming Soon - Start Bootstrap Theme</title>
        <link rel="stylesheet" href={% static "css/bootstrap.css" %}>
        <link rel="icon" type="image/x-icon" href="{% static "image/fav.png" %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&amp;display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&amp;display=swap" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static "comingsoon/css/styles.css" %}" />

    </head>
    <body>
        <!-- Background Video-->
        <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop"><source src="{% static "comingsoon/assets/mp4/bg.mp4" %}" type="video/mp4" /></video>
        <!-- Masthead-->
        <div class="masthead">
            <div class="masthead-content text-white">
                <div class="container-fluid px-4 px-lg-0">
                    <h1 class="fst-italic lh-1 mb-4">Our Website is Coming Soon</h1>
                    <p class="mb-5">We're working hard to finish the development of this site. Sign up below to receive updates and to be notified when we launch!</p>
                    <form id="contactForm"  action="/" method="post">
                        <!-- Email address input-->
                        {% csrf_token %}
                        <div class="row input-group-newsletter">
                            <div class="col"><input class="form-control" id="email" name="email" type="email" placeholder="Enter email address..." aria-label="Enter email address..." required /></div>
                            <div class="col-auto  col-xs-4 text-center"><button class="btn btn-primary " id="submitButton" type="submit">Notify Me!</button></div>
                        </div>   
                        <div class="mt-4 mb-3 col-xs-4 text-center">
                            {{ form.captcha }}
                        </div>
                        <div class="row input-group-newsletter"></div>
                        {% include 'message.html' %}
                    </div>   
                    
                </form>
            </div>
        </div>
        </div>
        <!-- Social Icons-->
        <!-- For more icon options, visit https://fontawesome.com/icons?d=gallery&p=2&s=brands-->
        <div class="social-icons">
            <div class="d-flex flex-row flex-lg-column justify-content-center align-items-center h-100 mt-3 mt-lg-0">
                <a class="btn btn-dark m-3" href="#!"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-dark m-3" href="#!"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-dark m-3" href="#!"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static "comingsoon/js/scripts.js" %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="{% static "js/vendor/jquery-2.2.4.min.js" %}"></script>
        <script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
    

    </body>
</html>

templates/message.html
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
  </div>
  {% endfor %}
{% endif %}


<!-- {% if form.errors %}
<div class="alert alert-error">
<h4>Please fix the following errors</h4>
<ul>
    {% for field in form %}
    {% if field.errors %}
        {% for error in field.errors %}
        <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
        {% endfor %}
    {% endif %}
    {% endfor %}
</ul>
{% if form.non_field_errors %}
    {{ form.non_field_errors }}
{% endif %}
</div>
{% endif %} -->

<!-- <ul>
{% for m in messages %}
<script>
    alert('{{ m }}');
</script>
{% endfor %}
</ul> -->